
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a10
  description: remove-vm
  annotations:
    backstage.io/kubernetes-id: a10
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: neenspa/a10
spec:
  type: api
  lifecycle: production
  owner: amargheritini
